project: runs/train
exp_name: transfomer_bilstm
disable_wandb: true
wandb_pj_name: fog-challenge
entity: chrenx
root_dpath: data/rectified_data
device: cuda:7
device_info: NVIDIA TITAN RTX
save_and_sample_every: 10
save_best_model: true
seed: 42
batch_size: 64
learning_rate: 0.0002
train_num_steps: 10
block_size: 15552
block_stride: 972
patch_size: 18
fog_model_input_dim: 162
fog_model_dim: 320
fog_model_num_heads: 8
fog_model_num_encoder_layers: 5
fog_model_num_lstm_layers: 2
fog_model_first_dropout: 0.1
fog_model_encoder_dropout: 0.1
fog_model_mha_dropout: 0.0
feats_list:
- L_Ankle_Acc_X
- L_Ankle_Acc_Y
- L_Ankle_Acc_Z
- L_MidLatThigh_Acc_X
- L_MidLatThigh_Acc_Y
- L_MidLatThigh_Acc_Z
- LowerBack_Acc_X
- LowerBack_Acc_Y
- LowerBack_Acc_Z
save_dir: runs/train/transfomer_bilstm/2024_06_07_12:59:44.21
weights_dir: runs/train/transfomer_bilstm/2024_06_07_12:59:44.21/weights
